config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated do
      root "items#index", as: :authenticated_root
    end

    unauthenticated do
      root "devise/sessions#new", as: :unauthenticated_root
    end
  end

  resources :items

  get "inventory", to: "items#inventory"
  get "purchases", to: "items#purchases"
  get "sales", to: "items#sales"

  resources :products
end

app/models/item.rb
class Item < ApplicationRecord
  TYPE = %w[compra venta].freeze

  belongs_to :product

  def self.inventory
    query = %{
      SELECT
      items.id,
      items.product_id,
      SUM(
        CASE
          WHEN items.item_type = 0 THEN items.quantity ELSE - items.quantity
        END
      ) AS quantity,
      items.cost
      FROM
      items
      INNER JOIN
      products
      ON
      items.product_id = products.id
      GROUP BY
      items.product_id
      ORDER BY items.product_id ASC;}.gsub(/\s+/, " ").strip
    result = find_by_sql(query)
    return result
  end

  def self.inventory_to_csv
    column_names = %w{product_id product_name quantity total_cost}

    CSV.generate(headers: true) do |csv|
      csv << column_names

      Item.inventory.each do |item|
        csv << [item.product_id, item.product.name, item.quantity, item.quantity * item.cost]
      end
    end
  end

  def self.inventory_to_csv
    column_names = %w{product_id product_name quantity total_cost}

    CSV.generate(headers: true) do |csv|
      csv << column_names

      Item.inventory.each do |item|
        csv << [item.product_id, item.product.name, item.quantity, item.quantity * item.cost]
      end
    end
  end

  def self.purchases_to_csv
    column_names = %w{product_id product_name quantity cost}

    CSV.generate(headers: true) do |csv|
      csv << column_names

      Item.all.where(item_type: Item::TYPE.index("compra").to_i).each do |item|
        csv << [item.product_id, item.product.name, item.quantity, item.cost]
      end
    end
  end

  def self.sales_to_csv
    column_names = %w{product_id product_name quantity price}

    CSV.generate(headers: true) do |csv|
      csv << column_names

      Item.all.where(item_type: Item::TYPE.index("venta").to_i).each do |item|
        csv << [item.product_id, item.product.name, item.quantity, item.cost]
      end
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  # GET /items.csv
  def index
    @items = Item.all
  end

  # GET /inventory
  # GET /inventory.json
  # GET /inventory.csv
  def inventory
    @items = Item.inventory

    respond_to do |format|
      format.html
      format.json
      format.csv { send_data Item.inventory_to_csv, filename: "inventory-#{Date.today}.csv" }
    end
  end

  # GET /purchases
  # GET /purchases.csv
  def purchases
    @items = Item.all.where(item_type: Item::TYPE.index("compra").to_i)

    respond_to do |format|
      format.html
      format.json
      format.csv { send_data Item.purchases_to_csv, filename: "purchases-#{Date.today}.csv" }
    end
  end

  # GET /sales
  # GET /sales.csv
  def sales
    @items = Item.all.where(item_type: Item::TYPE.index("venta").to_i)

    respond_to do |format|
      format.html
      format.json
      format.csv { send_data Item.sales_to_csv, filename: "sales-#{Date.today}.csv" }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:product_id, :type, :quantity, :cost, :price)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :product_id %>
    <%= form.number_field :product_id, id: :item_product_id, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :item_type %>
    <%= form.select :item_type, Item::TYPE, {}, id: :item_type, include_blank: true, class: "custom-select" %>
  </div>

  <div class="form-group">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, id: :item_quantity, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :cost %>
    <%= form.number_field :cost, id: :item_cost, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.number_field :price, id: :item_price, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :created_at %>
    <%= form.date_field :created_at, id: :created_at, class: "form-control" %>
  </div>

  <hr/>

  <div class="actions">
    <%= form.submit(nil, {class: "btn btn-lg btn-primary btn-block"}) %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h2><%= t("editing_item") %></h2>
<div class="btn-group" role="group" aria-label="">
  <%= link_to t("show"), @item, {class: "btn btn-secondary"} %>
  <%= link_to t("back"), items_path, {class: "btn btn-secondary"} %>
</div>

<hr/>

<%= render 'form', item: @item %>

app/views/items/index.html.erb
<h2><%= t("items") %></h2>
<div class="btn-group" role="group" aria-label="">
  <%= link_to t("new_item"), new_item_path, {class: "btn btn-secondary"} %>
</div>

<hr/>

<div class="table-responsive">
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th><%= t("product") %></th>
        <th><%= t("type") %></th>
        <th><%= t("quantity") %></th>
        <th><%= t("cost") %></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= item.product.name %></td>
          <td><%= Item::TYPE[item.item_type].to_s.capitalize %></td>
          <td><%= item.quantity %></td>
          <td><%= item.cost %></td>
          <td><%= link_to t("show"), item %></td>
          <td><%= link_to t("edit"), edit_item_path(item) %></td>
          <td><%= link_to t("destroy"), item, method: :delete, data: { confirm: t("are_you_sure") } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/items/inventory.html.erb
<h2><%= t("inventory") %></h2>
<div class="btn-group" role="group" aria-label="">
  <%= link_to t("new_item"), new_item_path, {class: "btn btn-secondary"} %>
  <%= link_to t("export_to_csv"), inventory_path(format: :csv), {class: "btn btn-secondary"} %>
</div>

<hr/>

<div class="table-responsive">
  <table class="table table-striped table-sm">
    <thead>
    <tr>
      <th><%= t("product") %></th>
      <th><%= t("quantity") %></th>
      <th><%= t("total_cost") %></th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.product.name %></td>
        <td><%= item.quantity %></td>
        <td><%= item.quantity * item.cost %></td>
        <td><%= link_to t("show"), item %></td>
        <td><%= link_to t("edit"), edit_item_path(item) %></td>
        <td><%= link_to t("destroy"), item, method: :delete, data: {confirm: t("are_you_sure")} %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/items/new.html.erb
<h2><%= t("new_item") %></h2>
<div class="btn-group" role="group" aria-label="">
  <%= link_to t("back"), items_path, {class: "btn btn-secondary"} %>
</div>

<hr/>

<%= render 'form', item: @item %>

app/views/items/purchases.html.erb
<h2><%= t("purchases") %></h2>
<div class="btn-group" role="group" aria-label="">
  <%= link_to t("new_item"), new_item_path, {class: "btn btn-secondary"} %>
  <%= link_to t("export_to_csv"), purchases_path(format: :csv), {class: "btn btn-secondary"} %>
</div>

<hr/>

<div class="table-responsive">
  <table class="table table-striped table-sm">
    <thead>
    <tr>
      <th><%= t("product") %></th>
      <th><%= t("quantity") %></th>
      <th><%= t("cost") %></th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.product.name %></td>
        <td><%= item.quantity %></td>
        <td><%= item.cost %></td>
        <td><%= link_to t("show"), item %></td>
        <td><%= link_to t("edit"), edit_item_path(item) %></td>
        <td><%= link_to t("destroy"), item, method: :delete, data: {confirm: t("are_you_sure")} %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/items/sales.html.erb
<h2><%= t("sales") %></h2>
<div class="btn-group" role="group" aria-label="">
  <%= link_to t("new_item"), new_item_path, {class: "btn btn-secondary"} %>
  <%= link_to t("export_to_csv"), sales_path(format: :csv), {class: "btn btn-secondary"} %>
</div>

<hr/>

<div class="table-responsive">
  <table class="table table-striped table-sm">
    <thead>
    <tr>
      <th><%= t("product") %></th>
      <th><%= t("quantity") %></th>
      <th><%= t("price") %></th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.product.name %></td>
        <td><%= item.quantity %></td>
        <td><%= item.cost %></td>
        <td><%= link_to t("show"), item %></td>
        <td><%= link_to t("edit"), edit_item_path(item) %></td>
        <td><%= link_to t("destroy"), item, method: :delete, data: {confirm: t("are_you_sure")} %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/items/show.html.erb
<div class="btn-group" role="group" aria-label="">
  <%= link_to t("edit"), edit_item_path(@item), {class: "btn btn-secondary"} %>
  <%= link_to t("back"), items_path, {class: "btn btn-secondary"} %>
</div>

<hr/>

<div class="jumbotron"><div class="container">
  <p>
    <strong><%= t("product") %>:</strong>
    <%= @item.product_id %>
  </p>

  <p>
    <strong><%= t("type") %>:</strong>
    <%= Item::TYPE[@item.item_type] %>
  </p>

  <p>
    <strong><%= t("quantity") %>:</strong>
    <%= @item.quantity %>
  </p>

  <p>
    <strong><%= t("cost") %>:</strong>
    <%= @item.cost %>
  </p>

  <p>
    <strong><%= t("price") %>:</strong>
    <%= @item.price %>
  </p>
</div></div>